let finalReport = "";
let finalData = {};

function analyzeSkills() {
    const name = document.getElementById("username").value;
    const role = document.getElementById("role").value;
    const checkedSkills = document.querySelectorAll("input[type='checkbox']:checked");

    if (name === "") {
        alert("Please enter your name!");
        return;
    }

    let userSkills = [];
    checkedSkills.forEach(skill => userSkills.push(skill.value));

    const roleSkills = {
        "Frontend Developer": ["HTML", "CSS", "JavaScript", "React"],
        "Backend Developer": ["Java", "Spring Boot", "SQL"],
        "Full Stack Developer": ["HTML", "CSS", "JavaScript", "React", "Java", "Spring Boot", "SQL"],
        "Data Analyst": ["Python", "SQL", "Excel", "Power BI"]
    };

    let requiredSkills = roleSkills[role];
    let missingSkills = requiredSkills.filter(skill => !userSkills.includes(skill));

    let score = Math.round((userSkills.length / requiredSkills.length) * 100);
    if (score > 100) score = 100;

    let suggestion = missingSkills.length === 0
        ? "Excellent! You are job ready!"
        : "🚀 AI Suggestion: Focus on " + missingSkills.join(", ") + " to strengthen your profile.";

    // Store for PDF
    finalData = { name, role, userSkills, missingSkills, score, suggestion };

    // Stylish HTML Report
    document.getElementById("result").innerHTML = `
        <div class="report-card">
            <h2>AI Skill Analysis Report</h2>
            <p>Hello <span class="highlight">${name}</span>,</p>
            <p><strong>Target Role:</strong> ${role}</p>
            <p><strong>Your Skills:</strong> ${userSkills.join(", ") || "None"}</p>
            <p><strong>Missing Skills:</strong> 
                <span class="${missingSkills.length ? 'missing' : 'success'}">
                    ${missingSkills.length ? missingSkills.join(", ") : "None 🎉"}
                </span>
            </p>

            <div class="score-box">
                Skill Match Score: <span class="highlight">${score}%</span>
            </div>

            <p style="margin-top:15px;">${suggestion}</p>
        </div>
    `;
}
function downloadPDF() {
    if (!finalData.name) {
        alert("Please analyze first!");
        return;
    }

    const { jsPDF } = window.jspdf;
    const doc = new jsPDF("p", "mm", "a4");

    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    let y = 20;

    // ===== Title =====
    doc.setFont("helvetica", "bold");
    doc.setFontSize(18);
    doc.setTextColor(0, 76, 153);
    doc.text("AI Skill Gap Analysis Report", pageWidth / 2, y, { align: "center" });

    y += 8;
    doc.setDrawColor(0, 76, 153);
    doc.line(margin, y, pageWidth - margin, y);

    y += 15;

    // Reset font
    doc.setFont("helvetica", "normal");
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);

    // ===== Helper function for clean row format =====
    function addRow(label, value) {
        doc.setFont("helvetica", "bold");
        doc.text(label, margin, y);

        doc.setFont("helvetica", "normal");

        const splitText = doc.splitTextToSize(value, pageWidth - margin * 2);
        y += 7;
        doc.text(splitText, margin, y);

        y += splitText.length * 7 + 3;
    }

    // ===== Content =====
    addRow("Candidate Name:", finalData.name);
    addRow("Target Role:", finalData.role);
    addRow("Your Skills:", finalData.userSkills.join(", ") || "None");
    addRow("Missing Skills:", finalData.missingSkills.join(", ") || "None");
    addRow("Skill Match Score:", finalData.score + "%");

    // ===== Recommendation Section =====
    doc.setFont("helvetica", "bold");
    doc.setTextColor(0, 128, 0);
    doc.text("AI Recommendation:", margin, y);

    y += 8;
    doc.setFont("helvetica", "normal");
    doc.setTextColor(0, 0, 0);

    const cleanSuggestion = finalData.suggestion.replace(/[^\x00-\x7F]/g, ""); 
    const wrappedSuggestion = doc.splitTextToSize(cleanSuggestion, pageWidth - margin * 2);

    doc.text(wrappedSuggestion, margin, y);

    // ===== Footer =====
    doc.setFontSize(10);
    doc.setTextColor(120);
    doc.text(
        "Generated by AI Skill Gap Analyzer | Developed by Swathi",
        pageWidth / 2,
        285,
        { align: "center" }
    );

    doc.save("AI_Skill_Report.pdf");
}